substitutions:
  name: "esp-cam"
  friendly_name: "ESP32 Camera"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: fabio_garavini.esp-cam-frigate
    version: "1.0.1"

esp32:
  board: esp32cam
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: <your-esp-encryption-key>   #<-- You can uncomment and add your encryption key or leave it as it is

ota:
  platform: esphome
#  password: <your-esp-ota-password>  #<-- You can uncomment and add your OTA password or leave it as it is

dashboard_import:
  package_import_url: github://fabio-garavini/ESP32-Cam-Frigate/esphome-config.yaml@main
  import_full_config: false

wifi:
#  ssid: !secret wifi_ssid            #<-- You need to manually set your wifi credentials: wifi_ssid and wifi_password
#  password: !secret wifi_password    #    write them in your secrets file
  ap:
    ssid: "${friendly_name}"
    password: "6J1kOOlKiVdF"

captive_portal:

i2c:
  - id: camera_i2c
    sda: GPIO26
    scl: GPIO27

# Ai-Thinker ESP32-CAM
esp32_camera:
  name: Camera
  internal: true  # or false   <-- if you don't want to use Frigate
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_id: camera_i2c
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 15
  agc_mode: auto
  agc_gain_ceiling: 2x
  wb_mode: auto
  vertical_flip: true      #<-- you can cange this if you need
  horizontal_mirror: true  #<-- you can cange this if you need

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: gpio
    pin: GPIO4
    name: "Flash"
